######################################
# PostGIS container for Padre1 GEODATA instance
######################################
FROM camptocamp/postgis:9.6
MAINTAINER Jean Pommier <jean.pommier@pi-geosolutions.fr>

ENV POSTGRES_USER geonetwork 
ENV POSTGRES_DB geodata
#ADD *.sql /docker-entrypoint-initdb.d/

