######################################
# PostgreSQL container for Padre1 geocatalog instance
######################################
FROM postgres:latest
MAINTAINER Jean Pommier <jean.pommier@pi-geosolutions.fr>

ENV POSTGRES_USER geonetwork 
ENV POSTGRES_DB geonetwork
#ADD *.sql /docker-entrypoint-initdb.d/

