FROM busybox:latest
MAINTAINER Jean Pommier <jean.pommier@pi-geosolutions.fr>
RUN mkdir -p /var/lib/postgresql/data/pgdata && mkdir -p /var/padre/gndata
VOLUME ["/var/lib/postgresql/data/pgdata", "/var/padre/gndata"]
